services:
  app:
    build:
      dockerfile: backend/Dockerfile
    container_name: WordleApp
    ports:
      - "8080:8080"
    mem_limit: 12g
    volumes:
      - ./backend:/app
      - ./backend/application/embedmodel/cc.ru.300.bin.gz:/app/application/embedmodel/cc.ru.300.bin.gz

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: WordleNginx
    mem_limit: 5g
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  app: